name: "❓ Question or Support Request"
description: Questions and requests for support
title: "[Question]"
labels: ["question"]
body:
  - type: textarea
    id: question_support_request
    attributes:
      label: ❓ Question or Support Request
    validations:
      required: true
