name: 🚀 Deploy website on releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.fpt_server }}
        username: ${{ secrets.fpt_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: 'MeOS/'
        local-dir: 'src/'
        security: loose
